#!/bin/sh

ENVROOT="~/Projects/bahmni"
ideaParams="$ENVROOT/openmrs-module-bahmniapps $ENVROOT/forks/possible-config"
chromeParams="https://bahmni.mingle.thoughtworks.com/projects/possible https://mail.google.com/mail/u/0/#inbox https://mail.google.com/mail/u/1/#inbox"
codeParams="$ENVROOT/bahmni-package"

iterm="open -a /Applications/iTerm.app"
idea="open -a /Applications/idea\ IntelliJ.app $ideaParams"
chrome="open -a /Applications/Google\ Chrome.app $chromeParams"
slack="open -a /Applications/Slack.app"
vagrantup="cd $ENVROOT/bahmni-vagrant && vagrant up && cd - && say 'Vagrant is Ready'"
code="open -a /Applications/Visual\ Studio\ Code.app $codeParams"

load (){
	eval $* > /dev/null 2>&1 &
}

echo "Loading DEV environment Parallely"
load ${vagrantup}
load ${idea}
load ${slack}
load ${chrome}
load ${iterm}
load ${code}
exit 0
